---
title: "Atividade 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(nnet)
library(plotly)

```

## 5.5

Approximate the following functions by using MLP:

a) f(x1, x2) = max(c(exp(-(x1^2)), exp(-2 * (x2^2)), (2 * exp(-0.5 * (x1^2 * x2^2))) ) )

```{r}

# Função para aproximação

fx <-  function(x1_list, x2_list) {

  index <- 1
  x_list <- c()

  for (x1 in x1_list){
    x2 <- x2_list[[index]]
    x <- max(c(exp(-(x1^2)), exp(-2 * (x2^2)), (2 * exp(-0.5 * ((x1^2) * (x2^2)))) ) )
    x_list <- c(x_list,x)
    index <- index + 1
}
  return(x_list)
} 


# Dataset de treino

x1 <- (10*runif(5000))
x2 <- (10*runif(5000))
y <- fx(x1,x2)

df_train <- data.frame(x1,x2)

# Dataset de teste

x11 <- (10*runif(1000))
x22 <- (10*runif(1000))
df_test <-  data.frame(x11,x22)
y_test <- fx(x11,x22)


# Rede Neural com um hidden layer, 6 neurons e 200 iterações

nn <- nnet(df_train, y, size=6, maxit=200, linout=TRUE)

y_pred <- predict(nn, df_test)

# dataset teste + pred
df <- data.frame(x11,x22, y_test, y_pred)
```

## Gráfico da função x função aproximada



```{r , echo=FALSE}

library(plotly)

names(df)[1] <- "x"
names(df)[2] <- "y"
names(df)[3] <- "z"
names(df)[4] <- "z_pred"


fig1 <- plot_ly(df)
fig1 <- fig1 %>% add_trace(x=~x, y=~y, z=~z, type = 'scatter3d', mode="markers",opacity = 0.5, marker = list(size = 2,color = "red"), name= 'z_true' )
fig1 <- fig1 %>% add_trace(x=~x, y=~y, z=~z_pred, type = 'scatter3d', mode="markers",opacity = 0.5, marker = list(size = 2,color = "blue"), name='z_pred' )

fig1



```

b) f(x,y) = 0.5 + 0.1 * ((x^2) * cos(y +3)) + 0.4* x * y* exp(1-(y^2))

```{r}

# Função para aproximação

fx <-  function(x_list, y_list) {

  index <- 1
  z_list <- c()

  for (x in x_list){
    y <- y_list[[index]]
    z <- 0.5 + 0.1 * ((x^2) * cos(y + 3)) + (0.4 * x * y* exp(1-(y^2)))
    z_list <- c(z_list,z)
    index <- index + 1
}
  return(z_list)
} 


# Dataset de treino

x1 <- (10*runif(5000))
x2 <- (10*runif(5000))
y <- fx(x1,x2)

df_train <- data.frame(x1,x2)

# Dataset de teste

x11 <- (10*runif(1000))
x22 <- (10*runif(1000))
df_test <-  data.frame(x11,x22)
y_test <- fx(x11,x22)


# Rede Neural com um hidden layer, 12 neurons e 200 iterações

nn <- nnet(df_train, y, size=12, maxit=1000, linout=TRUE)

y_pred <- predict(nn, df_test)

# Dataset teste + pred
df <- data.frame(x11,x22, y_test, y_pred)
```
## Gráfico 

```{r , echo=FALSE}


names(df)[1] <- "x"
names(df)[2] <- "y"
names(df)[3] <- "z"
names(df)[4] <- "z_pred"


fig1 <- plot_ly(df)
fig1 <- fig1 %>% add_trace(x=~x, y=~y, z=~z, type = 'scatter3d', mode="markers",opacity = 0.5, marker = list(size = 2,color = "red"), name= 'z_true' )
fig1 <- fig1 %>% add_trace(x=~x, y=~y, z=~z_pred, type = 'scatter3d', mode="markers",opacity = 0.5, marker = list(size = 2,color = "blue"), name='z_pred' )

fig1



```
